### ISSUE TITLE
Refactor to use http-digest-header lib

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/http-signature-zcap-invoke#14]
Now that multihash support is implemented in https://github.com/digitalbazaar/http-digest-header, 
refactor [main.js#L75](https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/master/main.js#L75) digest creation code to use the new lib

**Comment by JSAssassin** [comment]
Closing, implemented here https://github.com/digitalbazaar/http-signature-zcap-invoke/pull/15
