### ISSUE TITLE
LD key signers do not have an ID

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-zcap-invoke#17]
The implementation here is expecting the value from `SomeLDKeyPair.signer()` to include an `id` which is the `keyId`.  I audited the `signer` API in a few places and from what I can tell this has never been the case.

https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/main/main.js#L102

Also, the documentation for the `invocationSigner` parameter is described as "The invoker's key for signing.".  The expected input is not a key.

https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/main/main.js#L26

The test suite here was made to add an ID manually:

https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/11ea024763ffc671d0e2e31028be932ad54c8354/tests/10-sign.spec.js#L120-L121

Here's an old signer implementation from `crypto-ld@3`
https://github.com/digitalbazaar/crypto-ld/blob/v3.9.0/lib/Ed25519KeyPair.js#L452-L514

**Comment by mattcollier** [comment]
I found another instance where an `id` is being added to the signer: https://github.com/digitalbazaar/ezcap/blob/main/lib/util.js#L53-L56

**Comment by dlongley** [comment]
Addressed by #21.
