### ISSUE TITLE
Add unit tests and CI

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/http-signature-zcap-invoke#2]
Tests will cycle through both of `crypto-ld`'s keyPairs:
  - Ed25519KeyPair
  - RSAKeyPair

Each loop will ensure the following functionality:

  - should sign a valid root zCap
  - should sign a zCap with a capability string
  - should sign a zCap with a capability object
  - should sign a zCap with host in the headers.
  - should sign a zCap with a capabilityAction
  - should sign a zCap with out a capabilityAction
  - should sign a zCap with json (if no digest)
    - should add a `content-type:application/json` if not in headers.
  - should sign a zCap with out json.
  - should sign a zCap with a digest.
  - should sign with out host if in a browser
  - should sign even if headers are UPPERCASE.

Negative tests:
  - should NOT sign a zCap with out a method
  - should NOT sign a zCap with out headers
  - should NOT sign a zCap with out an invocationSigner
  - should NOT sign a zCap with out a url and host.
  - should NOT sign a zCap with invalid json.
  - should NOT sign a zCAP if the capability is an object with no id.

**Comment by aljones15** [comment]
Also need to know if this change is ok:
https://github.com/digitalbazaar/http-signature-zcap-invoke/commit/9ceebab7a6d872461f3d2d146bef1301e00018be

As we really should be throwing if there is no `invocationSigner`

**Comment by dlongley** [comment]
@aljones15, Yes, we do need that change to throw when there is no `invocationSigner`, but it should follow our code/style conventions for errors.

**Comment by aljones15** [comment]
> @aljones15, Yes, we do need that change to throw when there is no `invocationSigner`, but it should follow our code/style conventions for errors.

can you clarify what that means here as throwing a BedrockError in a client side library I'm not sure if possible, and using a DomException won't work in node. Example!!??

**Comment by aljones15** [comment]
Closing as another issue continues the tests: https://github.com/digitalbazaar/http-signature-zcap-invoke/issues
